[[task]]
feature = "project_files"
name = "design_document"
requirements = [ "use llm to generate document driving implementation of project prototype",]
context_files = [ 1,]
save_file = 1
assigned_to = "human"
status = "tested"

[[task]]
feature = "prototype"
name = "add_command"
requirements = [ "implement and manually test add command",]
context_files = [ 2, 3, 4, 5, 6,]
save_file = 4
assigned_to = "human"
status = "tested"

[[task]]
feature = "prototype"
name = "list_command"
requirements = [ "implement and manually test list command",]
context_files = [ 7, 5,]
save_file = 7
assigned_to = "human"
status = "tested"

[[task]]
feature = "prototype"
name = "edit_command"
requirements = [ "implement and manually test edit command",]
context_files = [ 8, 5,]
save_file = 8
assigned_to = "human"
status = "tested"

[[task]]
feature = "prototype"
name = "read_command"
requirements = [ "implement and manually test read command",]
context_files = [ 9, 5,]
save_file = 9
assigned_to = "human"
status = "tested"

[[task]]
feature = "prototype"
name = "delete_command"
requirements = [ "implement and manually test delete command",]
context_files = [ 10, 5, 3]
save_file = 10
assigned_to = "human"
status = "tested"